name: Markdown Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List markdown files
        run: find . -name '*.md' -print
